#!/bin/bash
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2021, 2024 nfitzen <https://github.com/nfitzen>

# A Bash function that transforms a date string into Discord's Unix time
# format, and copies it. Requires wl-clipboard if on Wayland and xclip
# otherwise. Place in ~/.bash_aliases or any other Bash source.

function cpddate () {
    if [ $# -eq 0 ]; then
        echo "Not enough arguments provided." >&2
        return 1
    fi
    if [[ "$1" == "--help" ]]; then
        cat <<EOF
cpddate <timestamp> [format]

Copies a Discord-formatted timestamp to the clipboard.
<timestamp> is any time specifier used by \`date\`.

[format] may be one of:

tT	Short Time
dD	Short/Long Date
fF	Short/Long Date/Time
R	Relative Time

Discord will treat f as the default.
EOF
    return 0
    fi
    if [[ -n "$2" && "$2" != [tTdDfFR] ]]; then
        echo "Must use a valid Discord timestamp style." >&2
        return 2
    fi
    string="$(date -d "$1" +'<t:%s')"
    if [ $# -ge 2 ]; then
        string="${string}:$2"
    fi
    string="${string}>"
    if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
        clip="wl-copy"
    else
        clip="xclip -selection clipboard"
    fi
    echo -n "$string" | ${clip}
}
